spring:
  application:
    name: parcel-registration
  datasource:
    url: jdbc:postgresql://localhost:5433/gisdb
    username: admin
    password: "1234"
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8084