server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
grpc:
  server:
    port: 9090
spring:
  application:
    name: "User-Management"
  web:
    resources:
      add-mappings: true


  # --- PostgreSQL Configuration (For User Profiles & Land Data) ---
  datasource:
    url: jdbc:postgresql://localhost:5432/land_management_db
    username: my_user
    password: my_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/land-management
# --- Custom Properties for your Registration API ---
keycloak-admin:
  server-url: http://localhost:8080
  realm: land-management
  client-id: user-service
  client-secret: LkHXfQjwNOdAEkQjtQMP5ESVjxrM87Hj

debug: true

logging:
  level:
    org.springframework.security: DEBUG
