spring:
  application:
    name: eureka-server
eureka:
  client:
    register-with-eureka: false   # server doesn’t register itself
    fetch-registry: false         # server doesn’t fetch registry
server:
  port: 8761