spring:
  application:
    name: request
  datasource:
    url: jdbc:postgresql://localhost:5432/transfer_db
    username: my_user
    password: my_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8082